"""empty message

Revision ID: 6ac7f4971236
Revises: f5c4c738eb99
Create Date: 2021-06-18 00:24:02.157515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ac7f4971236'
down_revision = 'f5c4c738eb99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity', sa.Column('activityId', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activity', 'activityId')
    # ### end Alembic commands ###
