"""empty message

Revision ID: bf4bd2de74b3
Revises: 6fee0ee0e52a
Create Date: 2021-06-09 01:21:39.608969

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bf4bd2de74b3'
down_revision = '6fee0ee0e52a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_onboarding', sa.Column('onboarding_completed_timestamp', sa.DateTime(), nullable=True))
    op.drop_column('user_onboarding', 'onboarding_completed')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_onboarding', sa.Column('onboarding_completed', mysql.DATETIME(), nullable=True))
    op.drop_column('user_onboarding', 'onboarding_completed_timestamp')
    # ### end Alembic commands ###
